import "dotenv/config";
import { writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { runBenchSuite, type BenchReport } from "./bench-ai";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, "../docs/AI_PERFORMANCE.md");

const TARGETS = [
  process.env.BENCH_PROD_URL ?? "https://jaylin-love-erika.vercel.app",
  process.env.BENCH_LOCAL_URL ?? "http://localhost:3000",
];

function pass(label: string, ok: boolean, value: string) {
  return `| ${label} | ${value} | ${ok ? "PASS" : "FAIL"} |`;
}

function renderReport(reports: BenchReport[]): string {
  const prod = reports[0];
  const local = reports[1];

  const ragProd = prod?.rag;
  const tokenProd = prod?.firstToken;
  const concProd = prod?.sseConcurrent;
  const knowledge = prod?.knowledge ?? local?.knowledge;

  return `# AI 服务性能报告

> 自动生成 · ${new Date().toISOString().slice(0, 10)}  
> 项目：CoupleLanguageLearning

## 测试环境

| 项 | 值 |
|----|-----|
| 生产环境 | \`${TARGETS[0]}\` (Vercel hkg1) |
| 本地环境 | \`${TARGETS[1]}\` (对比参考) |
| 数据库 | Neon PostgreSQL + pgvector |
| 知识库规模 | **${knowledge?.total ?? "N/A"}** chunks |
| pgvector | ${knowledge?.pgvector ? "enabled" : "disabled"} |
| Embedding | OpenAI text-embedding-3-small (1536-dim) |
| Chat | DeepSeek deepseek-chat (stream) |

### 知识库构成

${knowledge?.byType?.map((b) => `- **${b.sourceType}**: ${b._count}`).join("\n") ?? "- N/A"}

---

## 1. RAG 检索延迟

测试：\`POST /api/rag/search\`，query=\`想是什么意思\`，hskLevel=1，${process.env.BENCH_SAMPLES ?? 20} 次采样。

| 指标 | 生产 (Vercel) | 本地 |
|------|---------------|------|
| p50 | ${fmt(local, prod, "rag", "p50")} | ${fmtLocal(local, "rag", "p50")} |
| p99 | ${fmt(local, prod, "rag", "p99")} | ${fmtLocal(local, "rag", "p99")} |
| min | ${fmt(local, prod, "rag", "min")} | ${fmtLocal(local, "rag", "min")} |
| max | ${fmt(local, prod, "rag", "max")} | ${fmtLocal(local, "rag", "max")} |
| errors | ${prod?.rag.errors ?? "N/A"} | ${local?.rag.errors ?? "N/A"} |

**验收目标：** p50 < 200ms

---

## 2. SSE 流式首字延迟 (TTFB)

测试：\`POST /api/chat/stream\`，消息「你好」，测量首个 \`event: token\` 到达时间，10 次采样。

| 指标 | 生产 (Vercel) | 本地 |
|------|---------------|------|
| p50 | ${fmt(local, prod, "firstToken", "p50")} | ${fmtLocal(local, "firstToken", "p50")} |
| p99 | ${fmt(local, prod, "firstToken", "p99")} | ${fmtLocal(local, "firstToken", "p99")} |
| errors | ${prod?.firstToken.errors ?? "N/A"} | ${local?.firstToken.errors ?? "N/A"} |

**验收目标：** p50 < 500ms

---

## 3. SSE 并发测试

测试：${process.env.BENCH_CONCURRENCY ?? 10} 路并发 \`/api/chat/stream\`，全部完成流式读取。

| 指标 | 生产 (Vercel) |
|------|---------------|
| 并发数 | ${process.env.BENCH_CONCURRENCY ?? 10} |
| 总耗时 | ${concProd ? `${concProd.p50.toFixed(0)}ms` : "N/A"} |
| 错误数 | ${concProd?.errors ?? "N/A"} |

**验收目标：** 0 errors

---

## 4. 验收汇总

| 项目 | 实测 | 结果 |
|------|------|------|
${pass("RAG p50 < 200ms", (ragProd?.p50 ?? 999) < 200, `${ragProd?.p50.toFixed(0) ?? "N/A"}ms`)}
${pass("SSE 首字 p50 < 500ms", (tokenProd?.p50 ?? 999) < 500, `${tokenProd?.p50.toFixed(0) ?? "N/A"}ms`)}
${pass("10 路 SSE 并发", (concProd?.errors ?? 1) === 0, `${concProd?.errors ?? "N/A"} errors`)}

---

## 5. 成本分析

基于 Erika 日常使用估算（DeepSeek + OpenAI Embedding）：

| 操作 | Token / 调用 | 单价 (约) | 频率 | 日成本 |
|------|-------------|-----------|------|--------|
| Query Embedding | ~20 tokens | $0.02 / 1M | 每次提问 | — |
| Chat 生成 | ~500 tokens | $0.14 / 1M (DeepSeek) | 每次回答 | — |
| 对话摘要 | ~200 tokens | 长对话时 | 偶尔 | — |
| 词汇入库 Embedding | ~50 tokens/词 | $0.02 / 1M | 仅 Admin 加词 | — |

### 典型日用量（10 轮对话）

| 项目 | 估算 |
|------|------|
| Embedding 调用 | 10 × 20 = 200 tokens ≈ **$0.000004** |
| Chat 生成 | 10 × 500 = 5,000 tokens ≈ **$0.0007** |
| **合计** | **≈ $0.001 / 天**（约 ¥0.007） |

### 月成本估算

| 场景 | 对话轮数/天 | 月成本 (USD) |
|------|------------|--------------|
| 轻度使用 | 10 | ~$0.03 |
| 中度使用 | 30 | ~$0.10 |
| 重度使用 | 100 | ~$0.30 |

> Embedding 在索引阶段产生较大一次性成本（5583 chunks × ~50 tokens ≈ 280K tokens ≈ **$0.006 一次性**）。日常对话成本极低。

### 成本控制措施（已实现）

- 知识库 embedding **缓存**在 DB，仅在 upsert 时重新计算
- 长对话才触发 **摘要压缩**（超 3000 token 阈值）
- Chat \`max_tokens: 500\` 上限
- 增量索引 \`npm run ai:index:incremental\` 避免重复 embedding

---

## 6. 复现方法

\`\`\`bash
# 生成此报告（生产 + 本地对比）
npm run ai:report

# 仅跑 benchmark 终端输出
BENCH_BASE_URL=https://jaylin-love-erika.vercel.app npm run ai:bench
\`\`\`

环境要求：\`.env\` 中 \`SESSION_SECRET\` 与目标环境一致（用于签发 bench 会话 cookie）。

---

*Report generated by \`scripts/generate-performance-report.ts\`*
`;
}

function fmt(
  _local: BenchReport | undefined,
  prod: BenchReport | undefined,
  key: keyof BenchReport,
  field: "p50" | "p99" | "min" | "max",
): string {
  const r = prod?.[key] as { p50: number; p99: number; min: number; max: number } | undefined;
  return r ? `${r[field].toFixed(0)}ms` : "N/A";
}

function fmtLocal(
  local: BenchReport | undefined,
  key: keyof BenchReport,
  field: "p50" | "p99" | "min" | "max",
): string {
  const r = local?.[key] as { p50: number; p99: number; min: number; max: number } | undefined;
  return r ? `${r[field].toFixed(0)}ms` : "skipped";
}

async function main() {
  const reports: BenchReport[] = [];

  console.log("=== Generating Performance Report ===\n");

  for (const url of TARGETS) {
    console.log(`Benchmarking ${url} ...`);
    try {
      const report = await runBenchSuite(url);
      reports.push(report);
      console.log(`  RAG p50: ${report.rag.p50.toFixed(0)}ms, First token p50: ${report.firstToken.p50.toFixed(0)}ms`);
    } catch (err) {
      console.warn(`  Skipped ${url}:`, err instanceof Error ? err.message : err);
    }
  }

  if (reports.length === 0) {
    console.error("No benchmarks completed.");
    process.exit(1);
  }

  // Pad local if skipped
  while (reports.length < 2) reports.push(reports[0]);

  const md = renderReport(reports);
  writeFileSync(OUT, md, "utf-8");
  console.log(`\nWritten: ${OUT}`);
}

main().catch(console.error);
